AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Agent Management Portal - AWS Infrastructure

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod

  ClaudeApiKey:
    Type: String
    Description: Anthropic API Key for Claude 4.5
    NoEcho: true

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs18.x
    MemorySize: 256
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        USECASES_TABLE: !Ref UseCasesTable
        AGENTS_TABLE: !Ref AgentsTable
        PERSONS_TABLE: !Ref PersonsTable
        TESTCASES_TABLE: !Ref TestCasesTable
        CLAUDE_API_KEY: !Ref ClaudeApiKey

Resources:
  # ==========================================
  # COGNITO - User Authentication
  # ==========================================

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub agent-portal-users-${Environment}

      # Email configuration
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email

      # Password policy
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false

      # Schema - custom attributes for role
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: role
          AttributeDataType: String
          Mutable: true
          Required: false

      # Lambda trigger for pre-signup validation (cisco.com only)
      LambdaConfig:
        PreSignUp: !GetAtt PreSignUpFunction.Arn

      # Email verification
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT

      # Account recovery
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: !Sub agent-portal-client-${Environment}
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      PreventUserExistenceErrors: ENABLED
      SupportedIdentityProviders:
        - COGNITO
      CallbackURLs:
        - http://localhost:3000
        - https://localhost:3000
      LogoutURLs:
        - http://localhost:3000
        - https://localhost:3000

  # Cognito User Groups (Personas)
  RootAdminGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: root-admin
      Description: Root administrators with full access
      UserPoolId: !Ref UserPool
      Precedence: 0

  PMGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: pm
      Description: Project Managers
      UserPoolId: !Ref UserPool
      Precedence: 1

  SAGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: sa
      Description: Solution Architects
      UserPoolId: !Ref UserPool
      Precedence: 2

  PSAGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: psa
      Description: Principal Solution Architects
      UserPoolId: !Ref UserPool
      Precedence: 3

  TechLeadGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: tech-lead
      Description: Tech Leads
      UserPoolId: !Ref UserPool
      Precedence: 4

  DevTestGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: dev-test
      Description: Dev-Test Engineers
      UserPoolId: !Ref UserPool
      Precedence: 5

  AIEngineerGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: ai-engineer
      Description: AI Engineers
      UserPoolId: !Ref UserPool
      Precedence: 6

  TestingGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: testing
      Description: Testing Engineers
      UserPoolId: !Ref UserPool
      Precedence: 7

  # Pre-signup Lambda to validate cisco.com email
  PreSignUpFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub agent-portal-presignup-${Environment}
      Handler: presignup.handler
      CodeUri: ../lambda/auth/
      Description: Validates that only cisco.com emails can register

  PreSignUpPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt PreSignUpFunction.Arn
      Principal: cognito-idp.amazonaws.com
      SourceArn: !GetAtt UserPool.Arn

  # ==========================================
  # DYNAMODB TABLES
  # ==========================================

  UseCasesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub agent-portal-usecases-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: status-index
          KeySchema:
            - AttributeName: status
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  AgentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub agent-portal-agents-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: usecaseId
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: usecase-index
          KeySchema:
            - AttributeName: usecaseId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: status-index
          KeySchema:
            - AttributeName: status
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  PersonsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub agent-portal-persons-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: email-index
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  TestCasesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub agent-portal-testcases-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: usecaseId
          AttributeType: S
        - AttributeName: agentId
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: usecase-index
          KeySchema:
            - AttributeName: usecaseId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: agent-index
          KeySchema:
            - AttributeName: agentId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  # ==========================================
  # API GATEWAY
  # ==========================================

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub agent-portal-api-${Environment}
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt UserPool.Arn

  # ==========================================
  # LAMBDA FUNCTIONS
  # ==========================================

  # Use Cases CRUD
  UseCasesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub agent-portal-usecases-${Environment}
      Handler: usecases.handler
      CodeUri: ../lambda/api/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UseCasesTable
      Events:
        GetAll:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /usecases
            Method: GET
        GetOne:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /usecases/{id}
            Method: GET
        Create:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /usecases
            Method: POST
        Update:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /usecases/{id}
            Method: PUT
        Delete:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /usecases/{id}
            Method: DELETE

  # Agents CRUD
  AgentsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub agent-portal-agents-${Environment}
      Handler: agents.handler
      CodeUri: ../lambda/api/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AgentsTable
      Events:
        GetAll:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /agents
            Method: GET
        GetOne:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /agents/{id}
            Method: GET
        Create:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /agents
            Method: POST
        Update:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /agents/{id}
            Method: PUT
        Delete:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /agents/{id}
            Method: DELETE

  # Persons CRUD
  PersonsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub agent-portal-persons-${Environment}
      Handler: persons.handler
      CodeUri: ../lambda/api/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PersonsTable
      Events:
        GetAll:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /persons
            Method: GET
        GetOne:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /persons/{id}
            Method: GET
        Create:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /persons
            Method: POST
        Update:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /persons/{id}
            Method: PUT
        Delete:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /persons/{id}
            Method: DELETE

  # Test Cases CRUD
  TestCasesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub agent-portal-testcases-${Environment}
      Handler: testcases.handler
      CodeUri: ../lambda/api/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TestCasesTable
      Events:
        GetAll:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /testcases
            Method: GET
        GetOne:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /testcases/{id}
            Method: GET
        Create:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /testcases
            Method: POST
        Update:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /testcases/{id}
            Method: PUT
        Delete:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /testcases/{id}
            Method: DELETE

  # Chatbot Function (Claude 4.5)
  ChatbotFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub agent-portal-chatbot-${Environment}
      Handler: chatbot.handler
      CodeUri: ../lambda/chatbot/
      Timeout: 60
      MemorySize: 512
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UseCasesTable
        - DynamoDBReadPolicy:
            TableName: !Ref AgentsTable
        - DynamoDBReadPolicy:
            TableName: !Ref PersonsTable
        - DynamoDBReadPolicy:
            TableName: !Ref TestCasesTable
      Events:
        Chat:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /chat
            Method: POST

Outputs:
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
    Export:
      Name: !Sub ${AWS::StackName}-UserPoolId

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub ${AWS::StackName}-UserPoolClientId

  ApiUrl:
    Description: API Gateway URL
    Value: !Sub https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}
    Export:
      Name: !Sub ${AWS::StackName}-ApiUrl

  UseCasesTableName:
    Description: DynamoDB Use Cases Table
    Value: !Ref UseCasesTable

  AgentsTableName:
    Description: DynamoDB Agents Table
    Value: !Ref AgentsTable

  PersonsTableName:
    Description: DynamoDB Persons Table
    Value: !Ref PersonsTable

  TestCasesTableName:
    Description: DynamoDB Test Cases Table
    Value: !Ref TestCasesTable
